version: '3.9'
services:
  reprepro:
    build: .
    container_name: ${PIPELINE:-staging}-reprepro
    hostname: ${PIPELINE:-staging}-reprepro
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3142:3142"
