services:
  apt-cacher:
    build: .
    image: apt-cacher
    container_name: ${PIPELINE:-staging}-apt-cacher
    hostname: ${PIPELINE:-staging}-apt-cacher
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3142:3142"
