version: '3.9'
services:
  apt-cacher:
    build: .
    container_name: ${PIPELINE:-staging}-apt-cacher
    hostname: ${PIPELINE:-staging}-apt-cacher
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3142:3142"
